pygmentsUseClasses=true
pygmentsCodeFences=true
pygmentsStyle: "dracula"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
    max = "0.121.1"



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4
